"""initial notification center schema

Revision ID: 4ad8c89c24fc
Revises:
Create Date: 2026-08-18 20:57:08.401980

"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "4ad8c89c24fc"
down_revision: str | Sequence[str] | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "audit_logs",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("company_id", sa.String(length=64), nullable=True),
        sa.Column("actor_type", sa.String(length=40), nullable=False),
        sa.Column("actor_id", sa.String(length=120), nullable=False),
        sa.Column("action", sa.String(length=120), nullable=False),
        sa.Column("target_type", sa.String(length=80), nullable=False),
        sa.Column("target_id", sa.String(length=120), nullable=False),
        sa.Column("details", sa.JSON(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_audit_logs_action"), "audit_logs", ["action"], unique=False)
    op.create_index(op.f("ix_audit_logs_company_id"), "audit_logs", ["company_id"], unique=False)
    op.create_table(
        "companies",
        sa.Column("id", sa.String(length=64), nullable=False),
        sa.Column("name", sa.String(length=120), nullable=False),
        sa.Column("enabled", sa.Boolean(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "employees",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("company_id", sa.String(length=64), nullable=False),
        sa.Column("name", sa.String(length=120), nullable=False),
        sa.Column("department", sa.String(length=120), nullable=False),
        sa.Column("content_vertical", sa.String(length=160), nullable=False),
        sa.Column("secondary_topics", sa.JSON(), nullable=False),
        sa.Column("target_platforms", sa.JSON(), nullable=False),
        sa.Column("account_name", sa.String(length=160), nullable=False),
        sa.Column("tone", sa.String(length=160), nullable=False),
        sa.Column("video_duration_seconds", sa.Integer(), nullable=False),
        sa.Column("publishing_frequency", sa.String(length=120), nullable=False),
        sa.Column(
            "status",
            sa.Enum("ACTIVE", "DISABLED", "DEPARTED", "DELETED", name="employeestatus"),
            nullable=False,
        ),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["company_id"],
            ["companies.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_employees_company_id"), "employees", ["company_id"], unique=False)
    op.create_table(
        "users",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("username", sa.String(length=120), nullable=False),
        sa.Column("password_hash", sa.String(length=255), nullable=False),
        sa.Column(
            "role", sa.Enum("SUPER_ADMIN", "COMPANY_ADMIN", "VIEWER", name="role"), nullable=False
        ),
        sa.Column("company_id", sa.String(length=64), nullable=True),
        sa.Column("enabled", sa.Boolean(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["company_id"],
            ["companies.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_users_company_id"), "users", ["company_id"], unique=False)
    op.create_index(op.f("ix_users_username"), "users", ["username"], unique=True)
    op.create_table(
        "binding_codes",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("company_id", sa.String(length=64), nullable=False),
        sa.Column("employee_id", sa.String(length=36), nullable=False),
        sa.Column("code_hash", sa.String(length=64), nullable=False),
        sa.Column("expires_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("used_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["company_id"],
            ["companies.id"],
        ),
        sa.ForeignKeyConstraint(
            ["employee_id"],
            ["employees.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_binding_codes_code_hash"), "binding_codes", ["code_hash"], unique=True)
    op.create_index(
        op.f("ix_binding_codes_company_id"), "binding_codes", ["company_id"], unique=False
    )
    op.create_index(
        op.f("ix_binding_codes_employee_id"), "binding_codes", ["employee_id"], unique=False
    )
    op.create_table(
        "video_assets",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("company_id", sa.String(length=64), nullable=False),
        sa.Column("employee_id", sa.String(length=36), nullable=False),
        sa.Column("title", sa.String(length=240), nullable=False),
        sa.Column("caption", sa.Text(), nullable=False),
        sa.Column("original_filename", sa.String(length=255), nullable=False),
        sa.Column("storage_path", sa.Text(), nullable=False),
        sa.Column("content_type", sa.String(length=120), nullable=False),
        sa.Column("size_bytes", sa.Integer(), nullable=False),
        sa.Column("sha256", sa.String(length=64), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["company_id"],
            ["companies.id"],
        ),
        sa.ForeignKeyConstraint(
            ["employee_id"],
            ["employees.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_video_assets_company_id"), "video_assets", ["company_id"], unique=False
    )
    op.create_index(
        op.f("ix_video_assets_employee_id"), "video_assets", ["employee_id"], unique=False
    )
    op.create_table(
        "weixin_bindings",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("company_id", sa.String(length=64), nullable=False),
        sa.Column("employee_id", sa.String(length=36), nullable=False),
        sa.Column("account_id_encrypted", sa.Text(), nullable=False),
        sa.Column("user_id_encrypted", sa.Text(), nullable=False),
        sa.Column("chat_id_encrypted", sa.Text(), nullable=False),
        sa.Column("context_token_encrypted", sa.Text(), nullable=True),
        sa.Column("user_fingerprint", sa.String(length=64), nullable=False),
        sa.Column("user_id_masked", sa.String(length=40), nullable=False),
        sa.Column("chat_id_masked", sa.String(length=40), nullable=False),
        sa.Column("active", sa.Boolean(), nullable=False),
        sa.Column("bound_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("revoked_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("last_interaction_at", sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(
            ["company_id"],
            ["companies.id"],
        ),
        sa.ForeignKeyConstraint(
            ["employee_id"],
            ["employees.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_weixin_bindings_active"), "weixin_bindings", ["active"], unique=False)
    op.create_index(
        op.f("ix_weixin_bindings_company_id"), "weixin_bindings", ["company_id"], unique=False
    )
    op.create_index(
        op.f("ix_weixin_bindings_employee_id"), "weixin_bindings", ["employee_id"], unique=False
    )
    op.create_index(
        op.f("ix_weixin_bindings_user_fingerprint"),
        "weixin_bindings",
        ["user_fingerprint"],
        unique=False,
    )
    op.create_table(
        "deliveries",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("company_id", sa.String(length=64), nullable=False),
        sa.Column("employee_id", sa.String(length=36), nullable=False),
        sa.Column("video_asset_id", sa.String(length=36), nullable=False),
        sa.Column("idempotency_key", sa.String(length=200), nullable=False),
        sa.Column(
            "status",
            sa.Enum(
                "PENDING",
                "SENDING",
                "SENT",
                "CONFIRMED",
                "FAILED",
                "RETRYING",
                "WAITING_INTERACTION",
                "CANCELLED",
                name="deliverystatus",
            ),
            nullable=False,
        ),
        sa.Column("external_message_id", sa.String(length=200), nullable=True),
        sa.Column("failure_code", sa.String(length=100), nullable=True),
        sa.Column("failure_message", sa.Text(), nullable=True),
        sa.Column("retry_count", sa.Integer(), nullable=False),
        sa.Column("next_retry_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("confirmed_at", sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(
            ["company_id"],
            ["companies.id"],
        ),
        sa.ForeignKeyConstraint(
            ["employee_id"],
            ["employees.id"],
        ),
        sa.ForeignKeyConstraint(
            ["video_asset_id"],
            ["video_assets.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("company_id", "idempotency_key", name="uq_delivery_tenant_key"),
    )
    op.create_index(op.f("ix_deliveries_company_id"), "deliveries", ["company_id"], unique=False)
    op.create_index(op.f("ix_deliveries_employee_id"), "deliveries", ["employee_id"], unique=False)
    op.create_index(
        op.f("ix_deliveries_video_asset_id"), "deliveries", ["video_asset_id"], unique=False
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_deliveries_video_asset_id"), table_name="deliveries")
    op.drop_index(op.f("ix_deliveries_employee_id"), table_name="deliveries")
    op.drop_index(op.f("ix_deliveries_company_id"), table_name="deliveries")
    op.drop_table("deliveries")
    op.drop_index(op.f("ix_weixin_bindings_user_fingerprint"), table_name="weixin_bindings")
    op.drop_index(op.f("ix_weixin_bindings_employee_id"), table_name="weixin_bindings")
    op.drop_index(op.f("ix_weixin_bindings_company_id"), table_name="weixin_bindings")
    op.drop_index(op.f("ix_weixin_bindings_active"), table_name="weixin_bindings")
    op.drop_table("weixin_bindings")
    op.drop_index(op.f("ix_video_assets_employee_id"), table_name="video_assets")
    op.drop_index(op.f("ix_video_assets_company_id"), table_name="video_assets")
    op.drop_table("video_assets")
    op.drop_index(op.f("ix_binding_codes_employee_id"), table_name="binding_codes")
    op.drop_index(op.f("ix_binding_codes_company_id"), table_name="binding_codes")
    op.drop_index(op.f("ix_binding_codes_code_hash"), table_name="binding_codes")
    op.drop_table("binding_codes")
    op.drop_index(op.f("ix_users_username"), table_name="users")
    op.drop_index(op.f("ix_users_company_id"), table_name="users")
    op.drop_table("users")
    op.drop_index(op.f("ix_employees_company_id"), table_name="employees")
    op.drop_table("employees")
    op.drop_table("companies")
    op.drop_index(op.f("ix_audit_logs_company_id"), table_name="audit_logs")
    op.drop_index(op.f("ix_audit_logs_action"), table_name="audit_logs")
    op.drop_table("audit_logs")
    # ### end Alembic commands ###
